# coding: utf-8

import sys
from setuptools import setup, find_packages

NAME = "swagger_server"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["connexion"]

setup(
    name=NAME,
    version=VERSION,
    description="sdia-orchestrator",
    author_email="S.Koulouzis@uva.nl",
    url="",
    keywords=["Swagger", "sdia-orchestrator"],
    install_requires=REQUIRES,
    packages=find_packages(),
    package_data={'': ['swagger/swagger.yaml']},
    include_package_data=True,
    entry_points={
        'console_scripts': ['swagger_server=swagger_server.__main__:main']},
    long_description="""\
    Software Defined Infrastructure Automator orchestrator. Orchestrator for TOSCA workflows. Deploys, manages at runtime or undeploys a TOSCA topology of declarative workflows and imperative workflows. Generates declarative workflows which are automatically generated by the orchestrator based on nodes, relationships, and groups defined in the topology. The Orchestrator also executes imperative workflows which are manually specified.
    """
)
